import React from 'react'

export default function Projects() {
  return (
    <section className="projects" id="projects">
      <h2>Selected Projects</h2>
      <div className="grid">
        <article className="card">
          <h4>Automated Cropping for Better Image Quality in Computer Vision with YOLOv11</h4>
          <p>
            Built a transformation pipeline in Python with PyTorch to enhance image quality for downstream object defect
            detection.
          </p>
          <p className="muted">Python • Pytorch • Linux • MLFlow </p>
          <p className="muted">Project by Phoenix Contact</p>
        </article>

        <article className="card">
          <h4>Statistical Dashboard for industrial printer repair management</h4>
          <p>
            Created an interactive dashboard for managing many printers and their repair intervals. The data generated by
            this software can enable predictive maintenance use cases.
          </p>
          <p className="muted">C# • Blazor • SQL • Bootstrap</p>
          <p className="muted">Project by Phoenix Contact</p>
        </article>

        <article className="card">
          <h4>Replaner Assist for People Planning</h4>
          <p>
            A small mobile app for planning the allocation of people to recurring tasks, including automated WhatsApp
            messages, ICS Generation and reminders.
          </p>
          <p className="muted">Javascript • React Native • JSON • Expo</p>
          <p className="muted">Project by Me (currently working on)</p>
        </article>

        <article className="card">
          <h4>Phoenix Contact AES Quiz</h4>
          <p>
            A quiz app for training the employees of Phoenix Contact on the topic of AES (All Electric Society). 
            The quiz was accessible via a QR code, was built with Angular and hosted on a Raspberry Pi.
          </p>
          <p className="muted">Javascript • Angular • Raspberry Pi • SCSS</p>
          <p className="muted">Project by Phoenix Contact</p>
        </article>

        <article className="card">
          <h4>Fuelprices Dashboard</h4>
          <p>An interactive web app to help users find the next fuel stop with the best price.</p>
          <p className="muted">Python• Streamlit • RestAPI • Tankerkoenig API</p>
          <p className="muted">Project by TH OWL</p>
          <a href="https://github.com/alwinsiemensDSDS/Benzinpreise" target="_blank">Link zu Github</a>
          <br />
          <a href="https://benzinpreise-jtqng8xt14a.streamlit.app/" target="_blank">Link zu Demo</a>
        </article>

        <article className="card">
          <h4>BLE Autologout</h4>
          <p>
            A mobile app that connects to your Windows PC over Bluetooth Low Energy and uses signal strength to
            automatically lock your Windows screen when leaving the office.
          </p>
          <p className="muted">Java • Mobile App Dev • C# • WPF • Bluetooth Low Energy </p>
          <p className="muted">Project by TH OWL</p>
          <a href="https://github.com/alwinsiemensDSDS/BLE_Autologout_Android" target="_blank">Link zu Github</a>
        </article>

        <article className="card">
          <h4>Research Project: LLM for Circuits</h4>
          <p>
            A research project conducted by a group of three students to evaluate whether GPT-4 understands the
            physical concepts in an electrical circuit.
          </p>
          <p className="muted">Python • GPT-4 • LLM • OpenAI API </p>
          <p className="muted">Project by TH OWL and Fraunhofer IOSB-INA</p>
        </article>

        <article className="card">
          <h4>X2CNC - AI assisted Low Code CAM</h4>
          <p>
            X2CNC is a low code CAM software that uses AI to generate CNC code from different sources. The software is designed to
            be user-friendly and accessible to users with little to no experience in CNC programming. The software is currently in development and is expected to be released in the near future.
          </p>
          <p className="muted">C# • Blazor • GRBL • AI • Serial • Mathematics</p>
          <p className="muted">Project by Me (currently working on)</p>
        </article>

         <article className="card">
          <h4>Manuel Lopez Infantes</h4>
          <p>
            A portfolio website for Manuel Lopez Infantes, a seller for construction machinery. The website is designed to showcase his products and services, and to provide a way for potential customers to contact him. 
          </p>
          <p className="muted">React • Cloudflare • Automatic Deployment</p>
          <p className="muted">Project by Me</p>
          <a href="https://manuel-lopez-infantes.de/" target="_blank">Link zu Website</a>
        </article>
      </div>
    </section>
  )
}
